# Generated by Django 3.2.6 on 2021-08-24 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('categories', django_mysql.models.ListTextField(models.CharField(choices=[('Coche', 'Coche'), ('Moto', 'Moto')], max_length=40, verbose_name='Insurance_category'), size=63)),
                ('phone', models.CharField(blank=True, max_length=9, verbose_name='Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_price', models.FloatField(verbose_name='Cantidad_seguro')),
                ('insurance_category', models.CharField(choices=[('Coche', 'Coche'), ('Moto', 'Moto')], max_length=40, verbose_name='Insurance_category')),
                ('periodicity', models.CharField(choices=[('Mensualmente', 'Mensualmente'), ('Anualmente', 'Mensualmente')], max_length=20, verbose_name='periodicity')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='Detail')),
                ('coverage_end', models.DateField()),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurer', to='api_insurances.insurers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
