# Generated by Django 3.2.6 on 2021-08-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_insurances', '0002_alter_insurers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='periodicity',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Anual', 'Anual')], max_length=20, verbose_name='periodicity'),
        ),
    ]
